# Generated by Django 5.0.6 on 2024-09-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='like_count',
            field=models.IntegerField(default=1),
        ),
    ]
