# Generated by Django 5.0.6 on 2024-07-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0005_alter_news_image_url_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=700, null=True),
        ),
    ]
