# Generated by Django 5.0.6 on 2024-07-16 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0006_alter_news_image_url_alter_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summariese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary_text', models.TextField()),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='summarizer.news')),
            ],
        ),
    ]
