# Generated by Django 5.0.6 on 2024-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0007_summariese'),
    ]

    operations = [
        migrations.AddField(
            model_name='summariese',
            name='like_count',
            field=models.IntegerField(default=1),
        ),
    ]
