# Generated by Django 5.0.6 on 2024-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0008_summariese_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summariese',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
